name: build-binary

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  release:
    types: [created]

jobs:
  build-image-20-04:
    name: Build image 20.04
    uses: ./.github/workflows/build-binary-on-ubuntu.yaml
    with:
      ubuntu_version: 20.04
      filename: gerbv.tar.gz
      upload: ${{ github.event_name == 'release' && github.event.action == 'created' }}

  build-image-22-04:
    name: Build image 22.04
    uses: ./.github/workflows/build-binary-on-ubuntu.yaml
    with:
      ubuntu_version: 22.04
      filename: gerbv-22.04.tar.gz
      upload: ${{ github.event_name == 'release' && github.event.action == 'created' }}
